
-- USERS
CREATE TABLE `USERS` (
  `USER_ID` int(11) NOT NULL AUTO_INCREMENT,
  `USERNAME` varchar(255) NOT NULL,
  `PASSWORD` varchar(255) NOT NULL,
  `FULL_NAME` varchar(255) NOT NULL,
  `ROLE` enum('admin','client') NOT NULL DEFAULT 'client',
  `PROFILE_PIC` varchar(255) DEFAULT NULL,
  `POSITION` varchar(255) DEFAULT NULL,
  `DEPARTMENT_ID` int(11) DEFAULT NULL,
  `SUB_DEPARTMENT_ID` int(11) DEFAULT NULL,
  `CREATED_AT` timestamp NOT NULL DEFAULT current_timestamp(),
  `IS_DELETED` tinyint(1) DEFAULT 0,
  `DELETED_AT` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`USER_ID`),
  UNIQUE KEY `USERNAME` (`USERNAME`),
  FOREIGN KEY (`DEPARTMENT_ID`) REFERENCES `DEPARTMENTS` (`DEPARTMENT_ID`) ON DELETE SET NULL,
  FOREIGN KEY (`SUB_DEPARTMENT_ID`) REFERENCES `DEPARTMENTS` (`DEPARTMENT_ID`) ON DELETE SET NULL
);

-- DEPARTMENTS
CREATE TABLE `DEPARTMENTS` (
  `DEPARTMENT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `DEPARTMENT_NAME` varchar(255) NOT NULL,
  `DEPARTMENT_TYPE` enum('college','office') NOT NULL,
  `PARENT_DEPARTMENT_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`DEPARTMENT_ID`),
  UNIQUE KEY `DEPARTMENT_NAME_TYPE` (`DEPARTMENT_NAME`, `DEPARTMENT_TYPE`),
  FOREIGN KEY (`PARENT_DEPARTMENT_ID`) REFERENCES `DEPARTMENTS` (`DEPARTMENT_ID`) ON DELETE CASCADE
);

-- DOCUMENT_TYPES
CREATE TABLE `DOCUMENT_TYPES` (
  `TYPE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `TYPE_NAME` varchar(50) NOT NULL,
  `FIELD_NAME` varchar(255) DEFAULT NULL,
  `FIELD_LABEL` varchar(255) DEFAULT NULL,
  `FIELD_TYPE` enum('text','textarea','date') DEFAULT 'text',
  `IS_REQUIRED` tinyint(1) DEFAULT 1,
  PRIMARY KEY (`TYPE_ID`),
  UNIQUE KEY `TYPE_NAME_FIELD` (`TYPE_NAME`, `FIELD_NAME`)
);

-- FILES
CREATE TABLE `FILES` (
  `FILE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `PARENT_FILE_ID` int(11) DEFAULT NULL,
  `FILE_NAME` varchar(255) NOT NULL,
  `FILE_PATH` varchar(255) DEFAULT NULL,
  `UPLOAD_DATE` timestamp NOT NULL DEFAULT current_timestamp(),
  `USER_ID` int(11) DEFAULT NULL,
  `FILE_SIZE` bigint(20) DEFAULT NULL,
  `FILE_TYPE` enum('pdf','doc','docx','xls','xlsx','jpg','png','txt','zip','other') NOT NULL,
  `HARD_COPY_AVAILABLE` tinyint(1) DEFAULT 0,
  `IS_DELETED` tinyint(1) DEFAULT 0,
  `DELETED_AT` timestamp NULL DEFAULT NULL,
  `DOCUMENT_TYPE_ID` int(11) NOT NULL,
  `STATUS` enum('pending','accepted','rejected') DEFAULT 'pending',
  `METADATA` text DEFAULT NULL,
  PRIMARY KEY (`FILE_ID`),
  FOREIGN KEY (`PARENT_FILE_ID`) REFERENCES `FILES` (`FILE_ID`) ON DELETE SET NULL,
  FOREIGN KEY (`USER_ID`) REFERENCES `USERS` (`USER_ID`) ON DELETE SET NULL,
  FOREIGN KEY (`DOCUMENT_TYPE_ID`) REFERENCES `DOCUMENT_TYPES` (`TYPE_ID`) ON DELETE CASCADE
);

-- TRANSACTIONS
CREATE TABLE `TRANSACTIONS` (
  `TRANSACTION_ID` int(11) NOT NULL AUTO_INCREMENT,
  `FILE_ID` int(11) NOT NULL,
  `DEPARTMENT_ID` int(11) DEFAULT NULL,
  `TRANSACTION_STATUS` enum('pending','accepted','denied') DEFAULT 'pending',
  `TRANSACTION_TYPE` int(11) DEFAULT NULL,
  `TIME_SENT` timestamp NOT NULL DEFAULT current_timestamp(),
  `TIME_RECEIVED` timestamp NULL DEFAULT NULL,
  `RECIPIENT_ID` int(11) DEFAULT NULL,
  `SENDER_ID` int(11) NOT NULL,
  `TIME_ACCEPTED` timestamp NULL DEFAULT NULL,
  `TIME_DENIED` timestamp NULL DEFAULT NULL,
  `GRANTS_OWNERSHIP` tinyint(1) DEFAULT 0,
  PRIMARY KEY (`TRANSACTION_ID`),
  FOREIGN KEY (`FILE_ID`) REFERENCES `FILES` (`FILE_ID`) ON DELETE CASCADE,
  FOREIGN KEY (`DEPARTMENT_ID`) REFERENCES `DEPARTMENTS` (`DEPARTMENT_ID`) ON DELETE SET NULL,
  FOREIGN KEY (`TRANSACTION_TYPE`) REFERENCES `DOCUMENT_TYPES` (`TYPE_ID`) ON DELETE SET NULL,
  FOREIGN KEY (`RECIPIENT_ID`) REFERENCES `USERS` (`USER_ID`) ON DELETE SET NULL,
  FOREIGN KEY (`SENDER_ID`) REFERENCES `USERS` (`USER_ID`) ON DELETE CASCADE
);

-- STORAGE
CREATE TABLE `STORAGE` (
  `STORAGE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `FILE_ID` int(11) DEFAULT NULL,
  `CABINET_NAME` varchar(255) NOT NULL,
  `DEPARTMENT_ID` int(11) NOT NULL,
  `SUB_DEPARTMENT_ID` int(11) DEFAULT NULL,
  `LOCATION` varchar(255) NOT NULL,
  `LAYER` int(11) NOT NULL,
  `BOX` int(11) NOT NULL,
  `FOLDER` int(11) NOT NULL,
  `IS_OCCUPIED` tinyint(1) DEFAULT 0,
  `FILE_COUNT` int(11) NOT NULL DEFAULT 0,
  `FOLDER_CAPACITY` int(11) NOT NULL DEFAULT 5,
  PRIMARY KEY (`STORAGE_ID`),
  UNIQUE KEY `UNIQUE_LOCATION` (`CABINET_NAME`, `LAYER`, `BOX`, `FOLDER`),
  FOREIGN KEY (`FILE_ID`) REFERENCES `FILES` (`FILE_ID`) ON DELETE SET NULL,
  FOREIGN KEY (`DEPARTMENT_ID`) REFERENCES `DEPARTMENTS` (`DEPARTMENT_ID`) ON DELETE CASCADE,
  FOREIGN KEY (`SUB_DEPARTMENT_ID`) REFERENCES `DEPARTMENTS` (`DEPARTMENT_ID`) ON DELETE SET NULL
);

-- EVENTS
CREATE TABLE `EVENTS` (
  `EVENT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `USER_ID` int(11) NOT NULL,
  `ACTION` varchar(255) NOT NULL,
  `MESSAGE` text DEFAULT NULL,
  `FILE_ID` int(11) DEFAULT NULL,
  `DEPARTMENT_ID` int(11) DEFAULT NULL,
  `STATUS` enum('pending','accepted','denied','approved','rejected','completed') DEFAULT 'pending',
  `TIMESTAMP` timestamp NOT NULL DEFAULT current_timestamp(),
  `EVENT_TYPE` enum('uploaded','received','info','access_request','access_result','activity') NOT NULL DEFAULT 'activity',
  PRIMARY KEY (`EVENT_ID`),
  FOREIGN KEY (`USER_ID`) REFERENCES `USERS` (`USER_ID`) ON DELETE CASCADE,
  FOREIGN KEY (`FILE_ID`) REFERENCES `FILES` (`FILE_ID`) ON DELETE SET NULL,
  FOREIGN KEY (`DEPARTMENT_ID`) REFERENCES `DEPARTMENTS` (`DEPARTMENT_ID`) ON DELETE SET NULL
);

-- ACCESS_REQUESTS
CREATE TABLE `ACCESS_REQUESTS` (
  `REQUEST_ID` int(11) NOT NULL AUTO_INCREMENT,
  `REQUESTER_ID` int(11) NOT NULL,
  `FILE_ID` int(11) NOT NULL,
  `OWNER_ID` int(11) NOT NULL,
  `STATUS` enum('pending','approved','rejected') DEFAULT 'pending',
  `TIME_REQUESTED` timestamp NOT NULL DEFAULT current_timestamp(),
  `TIME_APPROVED` timestamp NULL DEFAULT NULL,
  `TIME_REJECTED` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`REQUEST_ID`),
  FOREIGN KEY (`REQUESTER_ID`) REFERENCES `USERS` (`USER_ID`) ON DELETE CASCADE,
  FOREIGN KEY (`FILE_ID`) REFERENCES `FILES` (`FILE_ID`) ON DELETE CASCADE,
  FOREIGN KEY (`OWNER_ID`) REFERENCES `USERS` (`USER_ID`) ON DELETE CASCADE
);
